[package]
name = "car_minimap"
version = "0.1.0"
edition = "2024"

[dependencies]
egui = "0.31.1"
gpsd = "0.1.2"
image = "0.25.6"
reqwest = "0.12.20"
serde = "1.0.219"
tokio = { version = "1.45.1", features = ["full"] }
