name: Build for Raspberry Pi

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions/setup-rust@v3
        with:
          rust-version: 'stable'
          target: armv7-unknown-linux-gnueabihf
      
      - name: Install cross
        run: cargo install cross --locked
      
      - name: Build for Raspberry Pi
        run: cross build --release --target armv7-unknown-linux-gnueabihf

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: raspberry-pi-build
          path: target/armv7-unknown-linux-gnueabihf/release/
