name: Build for Raspberry Pi
on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: 'stable'
      
      - name: Add ARMv7 target
        run: rustup target add armv7-unknown-linux-gnueabihf
      
      - name: Install cross
        run: cargo install cross
      
      - name: Build for Raspberry Pi
        run: cross build --target armv7-unknown-linux-gnueabihf

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: raspberry-pi-build
          path: target/armv7-unknown-linux-gnueabihf/release/